### ISSUE TITLE
VyOS configuration system integration

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#262]
http://vyos.net/wiki/Perl_API  http://vyos.net/wiki/Configuration_mode_templates

**Comment by pavel-odintsov** [comment]
Most important part of configuration of FastNetMon is a list of all subnets which processed by this machine I need some way to get this data from Quagga or another place :(

**Comment by pavel-odintsov** [comment]
```bash
cnf
23:10 show ip route ?
```

**Comment by dmbaturin** [comment]
I don't think this list can (or should) be produced automatically. The user should be able to specify which subnets count as processed by this machine. 

In case of core routers with multiple clients, peers, and providers the distinction between upstream and downstream and purely administrative rather than technical, I doubt there's a sensible way to tell one from another without asking the admin. I think it should be an explicit config option (options that can hold multiple values are easy to make, with the multi: tag).

**Comment by pavel-odintsov** [comment]
Thanks for answer. I definitely agree with you and will add CLI integration shortly.

**Comment by pavel-odintsov** [comment]
Works OK!

```bash
cd /opt/vyatta/share/vyatta-cfg/templates/service
mkdir fastnetmon
echo "help: FastNetMon - DDoS detection toolkit" > /opt/vyatta/share/vyatta-cfg/templates/service/fastnetmon/node.def
```

```bash
sudo mkdir /opt/vyatta/share/vyatta-cfg/templates/service/networks_list
sudo mkdir /opt/vyatta/share/vyatta-cfg/templates/service/networks_whitelist
```


```cd /opt/vyatta/share/vyatta-cfg/templates/service/networks_list
```

```
vim node.def
```

```bash
multi:
type: ipv4net
```

```
cd /opt/vyatta/share/vyatta-cfg/templates/service/networks_whitelist
```

```
vim node.def
```

```bash
multi:
type: ipv4net
```

```set service fastnetmon networks_list 10.10.10.0/24
set service fastnetmon networks_list 10.10.5.0/24```

Works well:
```show service fastnetmon networks_list```

**Comment by pavel-odintsov** [comment]
I see zero reasons to spent time on it because I see too few interest in FastNetMon from VyOS customers;(
