### ISSUE TITLE
src/sflow_plugin/sflow_collector.cpp getAddress() may read beyond buffer

### ISSUE THREAD

**Issue by green525** [pavel-odintsov/fastnetmon#351]
sflow_collector.cpp getAddress() function treats anything type != SFLADDRESSTYPE_IP_V4 as IPv6. E.g. getData32() might return 0 (in case it detects potential read beyond buffer). So before reading 16 bytes, you should check that type == SFLADDRESSTYPE_IP_V6 and that there's sufficient data in the buffer.

I suggest to call skipBytes() incl. result check before memcpy().

**Comment by pavel-odintsov** [comment]
Hello!

Thanks for deep dive into my code! This code originally got from http://sflow.org/developers/tools.php official page. Could you send this complaints to they too? You could improve reference code and help to many folks like me who stole they code :)

Actually... I do not like this parsers and thinking about full rewrite of they because... it's nightmare for support.

**Comment by green525** [comment]
I just wrote a lengthy bug report to InMon (their code base has a few more very similar issues), hoping they'll fix sflowtool.

**Comment by pavel-odintsov** [comment]
Nice! Looking forward for new version of sFlow Tools and I will backport all changes.

**Comment by green525** [comment]
sflowtool 3.36 has been released Neil. It's now also available on github: https://github.com/sflow/sflowtool ... I haven't rechecked the code though.

**Comment by pavel-odintsov** [comment]
Thanks! I will backport this code.

**Comment by pavel-odintsov** [comment]
We've migrated away from this code and completely reworked sflow plugin: https://github.com/pavel-odintsov/fastnetmon/pull/844
