### ISSUE TITLE
Pager duty integration

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#388]
https://developer.pagerduty.com/documentation/rest/webhooks

**Comment by pavel-odintsov** [comment]
So each NOC engineer should be notified in case of any troubles in network. So we could use PagerDuty for it. But in case really HUGE attacks we need physically dedicated network for this line (mobile phone, sms or something else).

**Comment by caquino** [comment]
@pavel-odintsov what about turning the email notification into a "general external script notification", this way it can be used to trigger an email or to send the alert to pagerduty.

IMHO you should try to avoid adding support to a lot of different integrations and tools on your codebase, it will turn the project hard to maintain on the future.

For example instead of email notifications you can have an alert-script, which can receive all the required information from STDIN or as command line arguments, this way it will be easier to integrate not only with pagerduty, but with anything the user fells necessary.

Also with this you can ship a contrib folder with example scripts.

Some ideas:
- Pagerduty
- Nagios/Icinga passive notification
- Firewall automation via script
- Integration with other routing engines like quagga or bird also can be written this way.

**Comment by pavel-odintsov** [comment]
Cassiano, thanks for detailed feedback! I like this idea to implement custom notifications scripts as external facility.

But some "must" things should be implemented in core (BGP for example). 

I'm moving to "actions" idea to offer capability for implementing custom actions in separate .so library.

**Comment by pavel-odintsov** [comment]
Would recommend implementing such things as "notify scripts" and contribute them to project :) As example, would recommend Slack integration: https://github.com/pavel-odintsov/fastnetmon/blob/master/src/scripts/notify_with_slack.sh

**Comment by pavel-odintsov** [comment]
Yes, I do not like idea to add all possible external APIs in core. Telegram/Slack support was implemented as callback scripts. Let's do PagerDuty same way.
