### ISSUE TITLE
Pipe error

### ISSUE THREAD

**Issue by AjdinGH** [pavel-odintsov/fastnetmon#558]
Hi,

we have huge attack today and fastnetmon didn't send commad to exabgp with this error:
`[ERROR] Can't open ExaBGP pipe /var/run/exabgp.cmd Ban is not executed
`

Can you please help me to resolve this issue?

**Comment by pavel-odintsov** [comment]
Hello!

It's not related with FastNetMon. It's just about inability to pass BGP announce to ExaBGP. It could be related with ExaBGP daemon itself. 

You could try to play with GoBGP but it's to complicated to run it from current version.

**Comment by AjdinGH** [comment]
How do you mean is's to complicated because GoBGP last version is 1.11.
Can you please tell me what is complicated part because we have huge issue with DDoS we need to mitigate it manual.

**Comment by pavel-odintsov** [comment]
Hello

I mean another idea. FastNetMon 1.1.3 has optional support for GOBGP buy you should build it manually because it's not integrated into installer script. 

As another option you could try FastNetMon 2.0 beta test, you could find more details about it here: https://groups.google.com/forum/#!topic/fastnetmon/VFL_6CZpusM

But it's too early beta.

**Comment by AjdinGH** [comment]
Hi,
Is there any way to automatic update fastnetmon?

Kind regards.

**Comment by pavel-odintsov** [comment]
Nop, we do not have automatic script for update. Just install it again and keep your configuration files.
