### ISSUE TITLE
Enable option to reload FastNetMon

### ISSUE THREAD

**Issue by pubyun** [pavel-odintsov/fastnetmon#610]
there are reload logic in script:

src/fastnetmon.service
src/fastnetmon_init_script_centos6
src/scripts/build_any_package.pl
#ExecReload=/bin/kill -s HUP $MAINPID

but there is no reload logic in fastnetmon.

**Comment by pavel-odintsov** [comment]
Reload is not aupported, sorry.

**Comment by pavel-odintsov** [comment]
Due to FastNetMon's performance-centered design we have no logic to gracefully restart it. Hard daemon restart is extremely fast and can be execute in less then second. So I do not think that we need to do it.

Any attempt to implement graceful restart will have significant performance penalty and we want to avoid such cases.
