### ISSUE TITLE
Fastnetmon supported input types?

### ISSUE THREAD

**Issue by vishnubraj** [pavel-odintsov/fastnetmon#673]
What are the Input methods supported In fastnetmon.. Basically we are using pmacct to listen for netflow data and we want to redirect the Pmacct output to fastnetmon input. below are the pmacct output methods.
Relational databases: MySQL, PostgreSQL and SQLite
noSQL databases: MongoDB and BerkeleyDB
AMQP message exchanges: RabbitMQ
Kafka message brokers
memory tables
flat files

Does fastnetmon supports any of this input?

**Comment by pavel-odintsov** [comment]
Hello!

Sorry, I missed your request for some reasons. We do not support any of these "input types". We support only Netflow protocols like Netflow, IPFIX or sFlow or even port mirror.

pmacct is a third party software and I have no idea about it behaviour under load. If you need to get all benefits from FastNetMon you need to feed traffic directly to it instead of intermediate boxes/applications.
