### ISSUE TITLE
Set sampling rate for AF_PACKET

### ISSUE THREAD

**Issue by madsushi** [pavel-odintsov/fastnetmon#790]
OS: Ubuntu 18.04.3 LTS

I'm using AF_PACKET for capturing traffic, as I wasn't able to get pf_ring working properly. This works fine, except for one thing.

Currently, my routers (Arista) are mirroring traffic to the server running FastNetMon. They are sampling the traffic at a 1:1000 rate, as the total bandwidth could exceed a 10 Gbps link. However, I can't find a way to scale up the AF_PACKET traffic by 1000. I was able to do this with pf_ring in the past, but I don't see a setting for setting the sampling rate of AF_PACKET traffic before it reaches FastNetMon. What's the best option?

Thank you!

**Comment by pavel-odintsov** [comment]
Hello!

Yes, we've removed PF_RING for packages shipped in official distro repositories because of non open source license.  Also, we have decided to deprecate it for all new distributions and keep it only for very old distros like CentOS 6.

Looks like you use this option https://github.com/pavel-odintsov/fastnetmon/blob/master/src/fastnetmon.conf#L90 

Unfortunately, we do not have it now in place but we may consider adding it. I'll change this ticket to feature request.

**Comment by pavel-odintsov** [comment]
I've added this support. Would you mind trying master branch this way?

```
wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
sudo perl fastnetmon_install.pl --use-git-master```

You will need to set this option in configuration file:
```
 mirror_af_packet_custom_sampling_rate = 1
```
